Modules/Admin/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('admin')->group(function() {
    Route::POST('login', 	['as' => 'login.create','uses' => 'Auth\LoginController@login']);
	Route::get('logout', 	['as' => 'admin.logout','uses' => 'Auth\LoginController@logout']);
	Route::get('login', 	['as' => 'admin.login',	'uses' => 'Auth\LoginController@adminLogin']);
	Route::get('/getsubcategories/{id}', 	['as' => 'admin.getsubcategories',	'uses' => 'CategoryController@showSubCategory']);
	Route::group(['middleware' => 'AuthAdmin'] , function(){
    	Route::get('/',['as' => 'admin.dashboard' , 'uses' => 'AdminController@index']);
    	Route::resource('state','StateController');
    	Route::resource('category','CategoryController')->only(['index','create','store']);
        Route::get('/category/edit/{id}/{lang}','CategoryController@edit')->name('category.edit');
        Route::put('/category/update/{id}/{lang}','CategoryController@update')->name('category.update');
        Route::get('category/delete/{id}','CategoryController@destroy')->name('category.destroy');
    	Route::resource('product','ProductController')->only(['index','store','update','destroy','show']);
        Route::get('product/create/{lang}/{id?}','ProductController@create')->name('product.create');
        Route::get('/product/edit/{id}/{lang}','ProductController@edit')->name('product.edit');
        Route::put('/product/update/{id}/{lang}','ProductController@update')->name('product.update');
    	Route::get('product/delete/{id}','ProductController@destroy')->name('product.destroy');    
        Route::get('/productattach/delete','ProductController@removeAttachment');
       
            // to create gold price
        Route::get('/create/goldprice','SettingController@goldpriceCreate')->name('goldprice.create');
        Route::post('goldprice','SettingController@saveGoldPrice')->name('goldprice.store');

              // to create gst price
        Route::get('/create/gst','SettingController@gstCreate')->name('gst.create');
        Route::post('gst','SettingController@saveGst')->name('gst.store');

        // hot item or not 
        Route::get('/hotproduct/{productid}/{status}','ProductController@hotproduct')->name('product.hotproduct');

        Route::get('/language/{type}','AdminController@setLanguage')->name('language.save');

        Route::resource('users','UsersController')->only(['index']);
        Route::get('orders' , ['as' => 'client-orders' , 'uses' => 'OrdersController@listOrder']);
        Route::get('orders/details/{id}' , ['as' => 'get-order-details' , 'uses' => 'OrdersController@showDetails']);
        Route::POST('update/delivery/date' , ['as' => 'update-delivery-date' , 'uses' => 'OrdersController@updateDeliveryDate']);
        Route::POST('update/delivery/status' , ['as' => 'update-delivery-status' , 'uses' => 'OrdersController@updateDeliveryStatus']);

	});
});

Modules/Admin/Entities/Product.php
<?php

namespace Modules\Admin\Entities;
use Modules\Admin\Entities\Attachment;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
	protected $table = 'products';
    protected $fillable = [
        'name','description','labour','inc_dec_labour','weight','purity','discountPrice','attachment_id','state_id','category_id','
        hot_product'
    ];
    public $timestamps = true;

    public function category(){
    	return $this->belongsTo('Modules\Admin\Entities\Category');
    }
     public function state(){
    	return $this->belongsTo('Modules\Admin\Entities\State');
    }

     public function language()
    {
        return $this->morphMany('Modules\Admin\Entities\Language', 'languageable');
    }

     public function order()
    {
        return $this->hasMany('App\Models\Order','product_id','id');
    }
    public function attachments(){
        return $this->morphMany(Attachment::class,'attachable');
    }
}

Modules/Admin/Http/Controllers/ProductController.php
<?php

namespace Modules\Admin\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
// use Illuminate\Routing\Controller;
use App\Http\Controllers\Controller;
use Modules\Admin\Entities\Category;
use Modules\Admin\Entities\Language;
use Modules\Admin\Entities\State;
use Modules\Admin\Entities\Product;
use Modules\Admin\Services\ProductService;
use Validator;
use Input;
use Modules\Admin\Http\Requests\CreateProductRequest;
use Modules\Admin\Http\Requests\UpdateProductRequest;
use Session;

class ProductController extends Controller
{

    public $prodService = '';
   

    /**
        * Create a new controller instance.
        *
        * @return void
    */
    public function __construct(ProductService $prodService)
    {
        $this->prodService = $prodService;
    }
    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index()
    {

        $product = $this->prodService->getProducts(); 
        return view('admin::product/index',compact('product'));
    }

    /**
     * Show the form for creating a new resource.
     * @return Response
     */
    public function create($lang,$pid=null)
    {
        $state = State::all();
        $selectcat =  Category::where('parent_id',0)->get();
        if($pid != null)
        {
            $pid = base64_decode($pid);
        }
        return view('admin::product/create',compact('selectcat','state','pid','lang'));
    }

    /**
     * Store a new product.
     * @param Request $request
     * @return Response
     */
    public function store(CreateProductRequest $request)
    {
        $validated = $request->validated();

        $product = $this->prodService->saveProduct($request);

        if($product['status']  == true)
        {
            Session::flash('alert-success','Product saved successfully');
            if($product['btn'] =='save')
            {
                Session::forget('type');
                return redirect()->route('product.index');
            }elseif($product['btn'] =='addHindi')
            {

                Session::put('type','hn');
                 return redirect()->route('product.create',['lang'=>'hn','pid'=>base64_encode($product['data'])]);
            }elseif($product['btn'] =='savehindi')
            {
                Session::forget('type');
                 return redirect()->route('product.index');
            }else{
            return back()->withErrors($product['message']);
            }
        }
    }

    /**
     * Show the specified resource.
     * @param int $id
     * @return Response
     */
    public function show($id)
    {
        $product = $this->prodService->productDetail($id);
       

        return view('admin::product/show',compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     * @param int $id
     * @return Response
     */
    public function edit($id,$lang)
    {
        $productId = base64_decode($id);
        if($lang == 'en')
        {
            $product = Product::with(['attachments'=> function($query){ 
            $data = $query->where(['type' => 'original'])->get();
        }])->find($productId);
            if($product->purity != null)
            {
                $purity = json_decode($product->purity,true);

            }else
            {
                $purity =[];
            }
        }else{
            
            $product = Language::where('attachable_id',$productId)->where('attachable_model','Product')->get();
            if(!$product->isEmpty()){
                $getproduct = $product->toArray();
                 $product = array_column($getproduct, 'text', 'type');
                 $product['id'] = $productId;
            }else{
                return back()->withErrors('No hindi product found');
            }
        } 
        $state = State::all();
        $selectcat =  Category::where('parent_id',0)->get();
        return view('admin::product/edit',compact('product','state','selectcat','purity','lang'));
    }

    /**
     * Update the product.
     * @param Request $request
     * @param int $id
     * @return Response
     */
    public function update(Request $request, $id,$lang)
    {

        $input = Input::except('_token');
        if($lang == 'en')
        {
            $validator =$this->validate($request, [
               'name' => 'required|string|max:100',
                'labour'    => 'required|numeric|max:15',
                'inc_dec_labour'    => 'required',
                'weight' => 'required|numeric',
                'purity.*'  => 'required|numeric',
                'prod_image' => 'required',
                'prod_image.*' => 'mimes:jpeg,png,jpg,gif'
           ]);  
        }else{
             $validator = $this->validate($request,[
                'name'  => 'required|string|max:100',
                'description'    => 'required|max:1000',
            ]);
        }
        
       // if ($validator->fails()) {
       //      return redirect()->back()->withErrors($validator)->withInput();
       // }
        
          $pId = base64_decode($id);
          $updateproduct = $this->prodService->updateProduct($request,$pId,$lang);
        if($updateproduct['status'] == true)
        {
            Session::flash('alert-success','Product Update successfully');
            return redirect()->route('product.index');
        }else{
             return back()->withErrors($updateproduct['message']);
        }
    }

    /**
     * Remove the specified resource from storage.
     * @param int $id
     * @return Response
     */
    public function destroy($id)
    {
        $deleteProduct= $this->prodService->deleteProduct($id);
       if($deleteProduct == true)
       {
            // Session::flash('alert-success','Category Delete successfully');
            return redirect()->route('product.index');
       }
    }

     /**
     * To add hot product in database.
     * @param int $productId,$statusid
     * @return Response
     */

    public function hotproduct($productId,$statusid)
    {
         $hotProduct = $this->prodService->hotproduct($productId,$statusid);
         if($hotProduct['status'] == true)
        {
            Session::flash('alert-success',$hotProduct['message']);
            return redirect()->route('product.index');
        }else{
            return back()->withErrors($hotProduct['message']);
        }
    }

      /**
     * To remove attachment in database.
     * @param  request
     * @return Response
     */
    public function removeAttachment(Request $request)
    {
        $status = $this->prodService->removeAttachment($request);
        if($status == true)
        {
            return response()->json(['status' => true]);
        }
        else{
            return response()->json(['status' => false]);
        }
    }

}

Modules/Admin/Resources/views/product/index.blade.php
@extends('admin::layouts.master')
	@section('addstyle')
    <link rel="stylesheet" href="{{asset('css/admin/assets/css/lib/datatable/dataTables.bootstrap.min.css')}}">
		<link rel="stylesheet" href="{{asset('css/admin/assets/css/sweetalert/sweetalert.css')}}">
	@endsection
  @section('content')
  <div class="flash-message">
        @foreach (['danger', 'warning', 'success', 'info'] as $msg)
          @if(Session::has('alert-' . $msg))

          <p class="alert alert-{{ $msg }}">{{ Session::get('alert-' . $msg) }} <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></p>
          @endif
        @endforeach
    </div> 
  	<div class="animated fadeIn">
    	<div class="row">

	        <div class="col-md-12">
	            <div class="card">
	                <div class="card-header">
	                    <strong class="card-title">Product List</strong>
	                </div>
	                <div class="card-body">

					             @if ($product->count())
                          <table id="bootstrap-data-table" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>#</th>
                                     <th></th>
                                    <th>Name</th>
                                    <!-- <th>Category</th> -->
                                    <th>weight</th>
                                    <th>Purity</th>
                                    <th>Hot Product</th>
                                    <th>Action</th>
                                   
                                </tr>
                            </thead>
                            <tbody>
                               @foreach ($product as $row)
                                <tr>
                                   <td>
                                        <label data-toggle="collapse" data-target="#demo_{{ $row->id}}" class="accordion-toggle"> <i class="fa fa-plus"></i></label>
              
                                    </td>
                                  <td>{{ $row->id }}</td>
                                  <td>{{ $row->name }}</td>
                                  <!-- <td>{{ $row->price }}</td> -->
                                  <td>{{ $row->weight }}</td>
                                  <td>{{ $row->purity }}</td>
                                  @if($row->hot_product == '0') 
                                  <td><a href="{{ route('product.hotproduct',[$row->id,1]) }}"><span class="badge badge-info">Make a hot item</span></td>
                                  @elseif($row->hot_product == '1')
                                    <td><a href="{{ route('product.hotproduct',[$row->id,0]) }}"><span class="badge badge-danger">Not a hot item</span></td>
                                  @endif
                                  <td style="display: inline-flex;">
                                  <a href="{{ route('product.edit',['id'=>base64_encode($row->id),'lang'=>'en']) }}" class="btn btn-primary btn-sm">Edit </a>  ||
                                    <a href="{{ route('product.edit',['id'=>base64_encode($row->id),'lang'=>'hn']) }}" class="btn btn-primary btn-sm">संपादित करें </a>  ||  
                                  <a href="{{route('product.destroy',$row->id) }}" data-toggle="tooltip" data-original-title="Delete" id="confirm_delete" class="confirm_delete btn btn-danger btn-sm">Delete</a> ||
                                   <a href="{{ route('product.show',base64_encode($row->id)) }}" class="btn btn-primary btn-sm">Show</a>    
                                  </td>
                                </tr>
                              @endforeach
                              
                            </tbody>
                          </table>
                     @endif
	                
	                </div>
	            </div>
	        </div>

	    </div>
	</div>
  @endsection
  @section('addscript')
   	<script src="{{asset('js/admin/assets/js/lib/data-table/datatables.min.js')}}"></script>
    <script src="{{asset('js/admin/assets/js/lib/data-table/dataTables.bootstrap.min.js')}}"></script>
    <script src="{{asset('js/admin/assets/js/lib/data-table/dataTables.buttons.min.js')}}"></script>
    <script src="{{asset('js/admin/assets/js/lib/data-table/buttons.bootstrap.min.js')}}"></script>
    <script src="{{asset('js/admin/assets/js/lib/data-table/jszip.min.js')}}"></script>
    <script src="{{asset('js/admin/assets/js/lib/data-table/vfs_fonts.js')}}"></script>
    <script src="{{asset('js/admin/assets/js/lib/data-table/buttons.html5.min.js')}}"></script>
    <script src="{{asset('js/admin/assets/js/lib/data-table/buttons.print.min.js')}}"></script>
    <script src="{{asset('js/admin/assets/js/lib/data-table/buttons.colVis.min.js')}}"></script>
    <script src="{{asset('js/admin/assets/js/init/datatables-init.js')}}"></script>
    <script src="{{asset('js/admin/assets/js/sweetalert/sweetalert.min.js')}}"></script>

    <script type="text/javascript">
        window.success = '{{ Session::get('success') }}';
        window.error = '{{ Session::get('error') }}';
    </script>
    <script src="{{asset('js/admin/assets/js/sweetalert/custom.js')}}"></script>
    <script type="text/javascript">
        $(document).ready(function() {
          $('#bootstrap-data-table-export').DataTable();
      } );
  </script>
 
  @endsection

Modules/Admin/Resources/views/product/show.blade.php
@extends('admin::layouts.master')
@section('addstyle')
<style type="text/css">
.showimage{
	width: 185px;
	height: 185px;
	margin-right: 10px;
	margin-bottom: 10px;
	float: left;
}
table td.attachfile{
	border-top: none;
}
</style>
@endsection
	@section('content')

	<div class="animated fadeIn">
    	<div class="row">
	       <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">
                        <strong class="card-title">Product Detail</strong>
                    </div>
                    <div class="card-body">
                    	@if(!empty($product))
                        <table class="table">
                            <thead>
	                        </thead>
	                        <tbody>
	                            <tr>
	                                <th>Product Name</th>
	                                <td>{{ (array_key_exists('name',$product) ? ucwords($product['name']) : '--' )}}</td>
	                            </tr>
	                          
	                            <tr>
	                                <th>Product Price</th>
	                                <td>{{ (array_key_exists('price',$product) ? $product['price'] : '--' )}}</td>
	                               
	                            </tr>
	                            <tr>
	                                <th>Weight</th>
	                                <td>{{ (array_key_exists('weight',$product) ? $product['weight'] : '--' )}}</td>
	                                
	                            </tr>
	                            <tr>
	                                <th>Carat/Purity</th>
	                                <td>{{ (array_key_exists('carat',$product) ? $product['carat'] : '--' )}}</td>
	                            </tr>
	                            <tr>
	                                <th>Product Created</th>
	                                <td>{{ (array_key_exists('created_at',$product) ? $product['created_at'] : '--' )}}</td>
	                            </tr>
	                            <tr>
	                                <th>Product Description</th>
	                                <td>{{ (array_key_exists('description',$product) ? $product['description'] : '--' )}}</td>
	                            </tr>

	                             <tr>
	                                <th>Discount Price</th>
	                                <td>{{ (array_key_exists('discount_price',$product) ? $product['discount_price'] : '--' )}}</td>
	                            </tr>
	                            @if(array_key_exists('category',$product))
		                            @if(!empty($product['category']))
		                            <tr>
		                                <th>Product Category</th>
		                                <td>{{ (array_key_exists('name',$product['category']) ? ucwords($product['category']['name']) : '--' )}}</td>
		                            </tr>
		                            @endif
	                            @endif
	                             @if(array_key_exists('state',$product))
		                            @if(!empty($product['state']))
		                            <tr>
		                                <th>State</th>
		                                <td>{{ (array_key_exists('name',$product['state']) ? ucwords($product['state']['name']) : '--' )}}</td>
		                            </tr>
		                            @endif
	                            @endif
	                        </tbody>
                    	</table>
                    	@endif
               	 	</div>
            	</div>
	    	</div>
		</div> 
		<div class="row">
	       <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">
                        <strong class="card-title">Product Attachments</strong>
                    </div>
                    <div class="card-body">
                    	@if(!empty($product))
                        <table class="table">
                            <thead>
                                
                              
	                        </thead>
	                        <tbody>
	                          	
	                            <tr>
                                	@if(!empty($product['attachments']))
			                                <td class="avatar attachfile" width="150">
	                                	@foreach($product['attachments'] as $val)
			                                	<div class="showimage">
			                                		<img src="{{ asset($val['path']) }}">
			                                	</div>
	                                	@endforeach
			                                	<div class="clearfix"></div>
			                                </td>
	                                @else
			                                <td class="attachfile">
			                                	<div class="text-center">
			                                		<h4>No Attachment Available</h4>
			                                	</div>
			                                </td>
                                	@endif
	                            </tr>
	                          
	                           
	                        </tbody>
                    	</table>
                    	@endif
               	 	</div>
            	</div>
	    	</div>
		</div> 
	</div>
	
	@endsection

	@section('addscript')
	<script>
</script>
	@endsection