Modules/Admin/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('admin')->group(function() {
    Route::POST('login', 	['as' => 'login.create','uses' => 'Auth\LoginController@login']);
	Route::get('logout', 	['as' => 'admin.logout','uses' => 'Auth\LoginController@logout']);
	Route::get('login', 	['as' => 'admin.login',	'uses' => 'Auth\LoginController@adminLogin']);
	Route::get('/getsubcategories/{id}', 	['as' => 'admin.getsubcategories',	'uses' => 'CategoryController@showSubCategory']);
	Route::group(['middleware' => 'AuthAdmin'] , function(){
    	Route::get('/',['as' => 'admin.dashboard' , 'uses' => 'AdminController@index']);
    	Route::resource('state','StateController');
    	Route::resource('category','CategoryController')->only(['index','create','store']);
        Route::get('/category/edit/{id}/{lang}','CategoryController@edit')->name('category.edit');
        Route::put('/category/update/{id}/{lang}','CategoryController@update')->name('category.update');
        Route::get('category/delete/{id}','CategoryController@destroy')->name('category.destroy');
    	Route::resource('product','ProductController')->only(['index','store','update','destroy','show']);
        Route::get('product/create/{lang}/{id?}','ProductController@create')->name('product.create');
        Route::get('/product/edit/{id}/{lang}','ProductController@edit')->name('product.edit');
        Route::put('/product/update/{id}/{lang}','ProductController@update')->name('product.update');
    	Route::get('product/delete/{id}','ProductController@destroy')->name('product.destroy');    
        Route::get('/productattach/delete','ProductController@removeAttachment');
       
            // to create gold price
        Route::get('/create/goldprice','SettingController@goldpriceCreate')->name('goldprice.create');
        Route::post('goldprice','SettingController@saveGoldPrice')->name('goldprice.store');

              // to create gst price
        Route::get('/create/gst','SettingController@gstCreate')->name('gst.create');
        Route::post('gst','SettingController@saveGst')->name('gst.store');

        // hot item or not 
        Route::get('/hotproduct/{productid}/{status}','ProductController@hotproduct')->name('product.hotproduct');

        Route::get('/language/{type}','AdminController@setLanguage')->name('language.save');

        Route::resource('users','UsersController')->only(['index']);
        Route::get('orders' , ['as' => 'client-orders' , 'uses' => 'OrdersController@listOrder']);
        Route::get('orders/details/{id}' , ['as' => 'get-order-details' , 'uses' => 'OrdersController@showDetails']);
        Route::POST('update/delivery/date' , ['as' => 'update-delivery-date' , 'uses' => 'OrdersController@updateDeliveryDate']);
        Route::POST('update/delivery/status' , ['as' => 'update-delivery-status' , 'uses' => 'OrdersController@updateDeliveryStatus']);

	});
});

Modules/Admin/Entities/State.php
<?php

namespace Modules\Admin\Entities;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class State extends Model
{
	use SoftDeletes;
	/**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'states';
    protected $dates = ['deleted_at'];
    protected $fillable = [
    		'name'
    ];
    public $timestamps = true;

    public function product(){
        return $this->belongsTo('Modules\Admin\Entities\Product','state_id','id');
    }
     public function language()
    {
        return $this->morphMany('Modules\Admin\Entities\Language', 'languageable');
    }
}

Modules/Admin/Http/Controllers/StateController.php
<?php

namespace Modules\Admin\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Modules\Admin\Entities\State;
use Modules\Admin\Http\Requests\CreateStateRequest;
use Modules\Admin\Http\Requests\UpdateStateRequest;
use Modules\Admin\Services\StateService;
use Session;

class StateController extends Controller
{


    public $stateService = '';
   

    /**
        * Create a new controller instance.
        *
        * @return void
    */
    public function __construct(StateService $stateService)
    {
        $this->stateService = $stateService;
    }

    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index()
    {
        $state = $this->stateService->allState();
        return view('admin::state/index', compact('state'));
    }

    /**
     * Show the form for creating a new resource.
     * @return Response
     */
    public function create()
    {
        return view('admin::state/create');
    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     * @return Response
     */
    public function store(CreateStateRequest $request)
    {
        $state = $this->stateService->saveState($request->all());
        if($state == true)
        {
            Session::flash('alert-success','State saved successfully');
            return redirect()->route('state.create');
        }

    }

    /**
     * Show the specified resource.
     * @param int $id
     * @return Response
     */
    public function show($id)
    {
        return view('admin::show');
    }

    /**
     * Show the form for editing the specified resource.
     * @param int $id
     * @return Response
     */
    public function edit($id)
    {
        $stateId = base64_decode($id);
        $state =   State::find($stateId);

        return view('admin::state/edit',compact('state'));
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param int $id
     * @return Response
     */
    public function update(UpdateStateRequest $request, $id)
    {
        $sId = base64_decode($id);
        $updatestate = $this->stateService->updateState($request->all(),$sId);
        if($updatestate == true)
        {
            Session::flash('alert-success','State Update successfully');
            return redirect()->route('state.index');
        }
    }

    /**
     * Remove the specified resource from storage.
     * @param int $id
     * @return Response
     */
    public function destroy($id)
    {
        $deleteState = $this->stateService->deleteState($id);
       if($deleteState == true)
       {
            Session::flash('alert-success','State Delete successfully');
            return redirect()->route('state.index');
       }
    }
}

Modules/Admin/Resources/views/state/create.blade.php
@extends('admin::layouts.master')

  @section('content')
	 <div class="row">
        <div class="col-lg-12">
            <div class="breadcrumbs">
                <div class="breadcrumbs-inner">
                    <div class="row m-0">
                        <div class="col-sm-4">
                            <div class="page-header float-left">
                                <div class="page-title">
                                    <h1>State</h1>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-8">
                            <div class="page-header float-right">
                                <div class="page-title">
                                    <ol class="breadcrumb text-right">
                                        <li><a href="#">Home</a></li>
                                        
                                        <li class="active">State</li>
                                    </ol>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="flash-message">
        @foreach (['danger', 'warning', 'success', 'info'] as $msg)
          @if(Session::has('alert-' . $msg))

          <p class="alert alert-{{ $msg }}">{{ Session::get('alert-' . $msg) }} <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></p>
          @endif
        @endforeach
    </div> 
    	  <!-- Animated -->
    <div class="animated fadeIn">
    	<div class="row">
    		<div class="col-md-12">
    			<div class="card">
                    <div class="card-header">
                        <strong>Save State</strong>
                    </div>
                    <div class="card-body card-block">
                           
                    	{!! Form::open(['route' => 'state.store','class' => 'form-horizontal','method' => 'post']) !!}
                            <div class="row form-group">
                                <div class="col col-md-3">
                                	{!! Form::label('stateName', 'State Name',['class'=> 'form-control-label']) !!}
                                	<!-- <label for="stateName" class=" form-control-label">State Name</label> -->
                                </div>
                                <div class="col-12 col-md-9">
                                	<!-- <input type="text" id="stateName" name="name" placeholder="Enter State Name..." class="form-control"> -->
                                	{!! Form::text('name', old('name'), ['class' => 'form-control','placeholder' => 'Enter State Name...','id' => 'stateName']) !!}
                                	@if($errors->has('name'))
		                                <span class="text-danger" role="alert">
		                                    <strong>{{ $errors->first('name') }}</strong>
		                                </span>
		                            @endif
                                </div>
                            </div>
                          	<div class="row form-group">
                          		<div class="offset-3 col-md-9">
                          			 <button type="submit" class="btn btn-primary"></i> Save State</button>
                          		</div>
                          	</div>
                   		{!! Form::close() !!}
                    </div>
                           
                </div>
    		</div>
    	</div>
    </div>

  @endsection

Modules/Admin/Resources/views/state/edit.blade.php
@extends('admin::layouts.master')

  @section('content')
	 <div class="row">
        <div class="col-lg-12">
            <div class="breadcrumbs">
                <div class="breadcrumbs-inner">
                    <div class="row m-0">
                        <div class="col-sm-4">
                            <div class="page-header float-left">
                                <div class="page-title">
                                    <h1>Edit State</h1>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-8">
                            <div class="page-header float-right">
                                <div class="page-title">
                                    <ol class="breadcrumb text-right">
                                        <li><a href="#">Home</a></li>
                                        <li><a href="#">State</a></li>
                                        
                                        <li class="active">Edit</li>
                                    </ol>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="flash-message">
        @foreach (['danger', 'warning', 'success', 'info'] as $msg)
          @if(Session::has('alert-' . $msg))

          <p class="alert alert-{{ $msg }}">{{ Session::get('alert-' . $msg) }} <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></p>
          @endif
        @endforeach
    </div> 
    	  <!-- Animated -->
    <div class="animated fadeIn">
    	<div class="row">
    		<div class="col-md-12">
    			<div class="card">
                    <div class="card-header">
                        <strong>Edit State</strong>
                    </div>
                    <div class="card-body card-block">
                           
                    	{!! Form::model($state,['route' => ['state.update',base64_encode($state->id)],'class' => 'form-horizontal','method' => 'PUT']) !!}
                            <div class="row form-group">
                                <div class="col col-md-3">
                                	{!! Form::label('stateName', 'State Name',['class'=> 'form-control-label']) !!}
                                	<!-- <label for="stateName" class=" form-control-label">State Name</label> -->
                                </div>
                                <div class="col-12 col-md-9">
                                	<!-- <input type="text" id="stateName" name="name" placeholder="Enter State Name..." class="form-control"> -->
                                	{!! Form::text('name', old('name',(isset($state->name) ? $state->name :'')), ['class' => 'form-control','placeholder' => 'Enter State Name...','id' => 'stateName']) !!}
                                	@if($errors->has('name'))
		                                <span class="text-danger" role="alert">
		                                    <strong>{{ $errors->first('name') }}</strong>
		                                </span>
		                            @endif
                                </div>
                            </div>
                          	<div class="row form-group">
                          		<div class="offset-3 col-md-9">
                          			 <button type="submit" class="btn btn-primary"> Update</button>
                          		</div>
                          	</div>
                   		{!! Form::close() !!}
                    </div>
                           
                </div>
    		</div>
    	</div>
    </div>

  @endsection

Modules/Admin/Resources/views/state/index.blade.php
@extends('admin::layouts.master')
	@section('addstyle')
		<link rel="stylesheet" href="{{asset('css/admin/assets/css/lib/datatable/dataTables.bootstrap.min.css')}}">
	@endsection
  @section('content')
  <div class="flash-message">
        @foreach (['danger', 'warning', 'success', 'info'] as $msg)
          @if(Session::has('alert-' . $msg))

          <p class="alert alert-{{ $msg }}">{{ Session::get('alert-' . $msg) }} <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></p>
          @endif
        @endforeach
    </div> 
  	<div class="animated fadeIn">
    	<div class="row">

	        <div class="col-md-12">
	            <div class="card">
	                <div class="card-header">
	                    <strong class="card-title">Data Table</strong>
	                </div>
	                <div class="card-body">

					             @if ($state->count())
	                        <table id="bootstrap-data-table" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Name</th>
                                    <th>Action</th>
                                   
                                </tr>
                            </thead>
                            <tbody>
                            	@foreach ($state as $row)
                                <tr>
                                    <td>{{ $row->id }}</td>
                                    <td>{{ $row->name }}</td>

                                    <td style="display: inline-flex;">
                                    	<a href="{{ route('state.edit',base64_encode($row->id)) }}" class="btn btn-primary btn-sm">Edit </a>  |  
                               			<form action="{{ route('state.destroy', $row->id)}}" method="post">
						                  @csrf
						                  @method('DELETE')
						                  <button class="btn btn-danger btn-sm"> Delete</button>
						                </form>
                                    </td>
                                    
                                </tr>
                            	
                            	@endforeach
                            </tbody>
                          </table>
	                    @else
	                    	<div class="text-center">
	                    		<h3>No result Found</h3>
	                    	</div>
	                    @endif
	                </div>
	            </div>
	        </div>

	    </div>
	</div>
  @endsection
  @section('addscript')
   	<script src="{{asset('js/admin/assets/js/lib/data-table/datatables.min.js')}}"></script>
    <script src="{{asset('js/admin/assets/js/lib/data-table/dataTables.bootstrap.min.js')}}"></script>
    <script src="{{asset('js/admin/assets/js/lib/data-table/dataTables.buttons.min.js')}}"></script>
    <script src="{{asset('js/admin/assets/js/lib/data-table/buttons.bootstrap.min.js')}}"></script>
    <script src="{{asset('js/admin/assets/js/lib/data-table/jszip.min.js')}}"></script>
    <script src="{{asset('js/admin/assets/js/lib/data-table/vfs_fonts.js')}}"></script>
    <script src="{{asset('js/admin/assets/js/lib/data-table/buttons.html5.min.js')}}"></script>
    <script src="{{asset('js/admin/assets/js/lib/data-table/buttons.print.min.js')}}"></script>
    <script src="{{asset('js/admin/assets/js/lib/data-table/buttons.colVis.min.js')}}"></script>
    <script src="{{asset('js/admin/assets/js/init/datatables-init.js')}}"></script>


    <script type="text/javascript">
        $(document).ready(function() {
          $('#bootstrap-data-table-export').DataTable();
      } );
  </script>

  @endsection